---
- name: Restart mariadb
  service:
    name: "{{ mariadb_daemon }}"
    state: restarted
  listen: mariadb_restart

- name: Stop MariaDB
  service:
    name: "{{ mariadb_daemon }}"
    state: stopped
  listen: mariadb_stopped